import Head from 'next/head';
import Image from 'next/image';
import Pill from '../Components/Pill';
import Form from '../Components/Form';
import HoverLink from '../Components/HoverLink';
import { useRef } from 'react';

const mySkills = [
	'HTML',
	'CSS',
	'JavaScript',
	'React',
	'React Native',
	'Redux',
	'jQuery',
	'Bootstrap',
	'Tailwind CSS',
	'Git'
];

export default function Home() {
	const myRef = useRef(null);
	const executeScroll = () => {
		myRef.current.scrollIntoView()
	}
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<section id="top" className="bg-stone-200 h-screen w-full flex justify-center items-center ">
					<div className="text-center">
						<h1 className="font-sans text-7xl font-bold">Hey, I&apos;m Sean</h1>
						<p className="mt-8 font-bold">Hey, I&apos;m a React Developer</p>
						<HoverLink href="#contact">Get in touch!</HoverLink>
						<button onClick={executeScroll}>scroll</button>
						{/* <a href="#contact" className="inline-block bg-black text-white py-2 px-8 mt-4 rounded-xl font-bold duration-300 transition-transform ease-out hover:-translate-y-2">Get in touch!</a> */}
						<a href="#aboutme">
							<div className="arrow" />
						</a>
					</div>
				</section>
				<section className="bg-stone-200 h-screen w-full pt-20" id="aboutme">
					<div className="w-full text-center mb-16">
						<h2 className="font-bold uppercase text-3xl ">About Me</h2>
						<p className="max-w-prose mx-auto mt-4">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
							labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
							laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
							voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
							cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</p>
					</div>
					<div className="grid grid-cols-2 mx-auto w-full container">
						<div className="pr-6">
							<h3 className="font-bold text-xl">Get to know me!</h3>
							<p className="mt-6">
								Hey! It&apos;s John Doe and Hey, I&apos;m a Frontend Web Developer located in Los
								Angeles. I&apos;ve done remote projects for agencies, consulted for startups, and
								collaborated with talented people to create digital products for both business and
								consumer use.
							</p>
							<p className="mt-4">
								Hey, I&apos;m a bit of a digital product junky. Over the years, I&apos;ve used hundreds
								of web and mobile apps in different industries and verticals. Feel free to contact me
								here.
							</p>
							<HoverLink href="#contact">Contact</HoverLink>
							{/* <button className="bg-black text-white py-2 px-8 mt-4 rounded-xl font-bold">Contact</button> */}
						</div>
						<div>
							<h3 className="font-bold text-xl">Skills</h3>
							<ul className="mt-6">
								{mySkills.map((skill) => {
									return <Pill key={skill}>{skill}</Pill>;
								})}
							</ul>
						</div>
					</div>
				</section>
				<section className="bg-stone-800 text-white h-screen w-full pt-10" id="contact" ref={myRef}>
					<div className="w-full text-center mb-16">
						<h2 className="font-bold uppercase text-3xl ">Contact</h2>
						<p className="max-w-prose mx-auto mt-4">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
							labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
							laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
							voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
							cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</p>
					</div>
					<Form />
				</section>
			</main>

			<footer>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
